import Foundation
import Testing
@testable import Tracexy

// MARK: - LinuxCookedImportTests

/// Opening a Linux cooked capture through the real readers.
///
/// The saved streaming path must fold exactly the sessions, five-tuples, byte
/// totals and decoded layers the batch builder does; Follow Stream must
/// reconstruct a cooked conversation with truthful per-frame provenance; and a
/// mixed-DLT pcapng must keep every per-frame link type through its metadata
/// inventory and a writer round-trip. Every fixture byte is generated by
/// ``LinuxCookedFixture`` and ``PacketBuilder`` from documentation-range addresses;
/// temp captures are per-test and removed.
@Suite("Linux cooked capture import")
struct LinuxCookedImportTests {
    // MARK: Internal

    // MARK: - Saved / batch equivalence

    @Test(
        "A saved cooked capture folds exactly the batch sessions in both file formats",
        arguments: [LinuxCookedHeader.Version.sll, .sll2]
    )
    func savedCookedCapturesMatchBatch(version: LinuxCookedHeader.Version) throws {
        let linkType = LinuxCookedFixture.linkType(version)
        let summaries = SessionBuilder.build(from: Self.capturedFrames(version), linkType: linkType)

        // Non-vacuous: three distinct sessions across four frames, none of which
        // lists the outer cooked framing in its protocol stack.
        #expect(summaries.count == 3)
        #expect(summaries.allSatisfy { !$0.protocolStack.contains(.linuxCooked) })
        #expect(summaries.allSatisfy { !$0.protocolStack.contains(.ethernet) })
        #expect(summaries.allSatisfy { $0.totalBytes > 0 })
        #expect(summaries.contains { $0.protocolStack.contains(.tcp) && $0.protocolStack.contains(.http) })
        #expect(summaries.contains { $0.protocolStack.contains(.dns) })
        #expect(summaries.contains { $0.protocolStack.contains(.arp) })

        let batch = SessionSnapshot.snapshots(summaries)

        try ReplayCorpus.withTemporaryFile(Self.classicBytes(version)) { url in
            let result = try SavedCaptureStreamLoader(contentsOf: url).load()
            #expect(result.format == .pcap)
            #expect(result.defaultLinkType == linkType)
            #expect(result.totalFrames == 4)
            #expect(result.completeness == .complete)
            #expect(result.metadata.linkTypeCounts == [CaptureLinkTypeCount(linkType: linkType, frameCount: 4)])
            #expect(result.metadata.undecodableLinkLayerFrameCount == 0)
            let saved = try savedRestoredSnapshots(from: url)
            #expect(saved == batch)
        }

        try ReplayCorpus.withTemporaryFile(Self.pcapngBytes(version), ext: "pcapng") { url in
            let result = try SavedCaptureStreamLoader(contentsOf: url).load()
            #expect(result.format == .pcapng)
            #expect(result.metadata.undecodableLinkLayerFrameCount == 0)
            let saved = try savedRestoredSnapshots(from: url)
            #expect(saved == batch)
        }
    }

    // MARK: - Follow Stream over a cooked source

    @Test(
        "Follow Stream reconstructs a cooked conversation with truthful frame provenance",
        arguments: [LinuxCookedHeader.Version.sll, .sll2]
    )
    func followStreamReconstructsCookedConversation(version: LinuxCookedHeader.Version) throws {
        try ReplayCorpus.withTemporaryFile(Self.classicBytes(version)) { url in
            let identity = try CaptureStreamReader(contentsOf: url).identity
            let result = try FollowStreamReader(
                contentsOf: url, expectedIdentity: identity, tuple: Self.tuple
            ).read()

            #expect(result.format == .pcap)
            #expect(result.tuple == Self.tuple)
            // The DNS and ARP frames are scanned but belong to other conversations.
            #expect(result.scannedFrameCount == 4)
            #expect(result.matchedFrameCount == 2)
            #expect(result.completeness == .complete)
            #expect(result.limitations.isEmpty)

            let runs = result.aToB.runs + result.bToA.runs
            #expect(runs.map(\.bytes).contains(Self.request))
            #expect(runs.map(\.bytes).contains(Self.response))
            // Provenance is the ordinal of the frame that first carried the bytes,
            // counted over the whole file — not over the matched subset.
            #expect(Set(runs.map(\.firstCaptureOrdinal)) == [1, 2])
        }
    }

    // MARK: - Mixed-DLT pcapng

    @Test("A mixed-DLT pcapng keeps every per-frame link type through its metadata and a writer round-trip")
    func mixedDLTPcapngPreservesLinkTypesAndRoundTrips() throws {
        let entries = Self.mixedDLTEntries
        let frames = entries.enumerated().map { index, entry in
            CapturedFrame(
                bytes: entry.bytes,
                timestamp: ReplayCorpus.epoch.addingTimeInterval(TimeInterval(index + 1)),
                originalLength: entry.bytes.count,
                linkType: entry.linkType
            )
        }
        // Each frame's own DLT decodes it, so the Ethernet default passed here is
        // never what resolves the two cooked frames.
        let summaries = SessionBuilder.build(from: frames, linkType: LinkType.ethernet)
        #expect(summaries.count == 3)
        #expect(summaries.allSatisfy { $0.protocolStack.contains(.http) })
        let batch = SessionSnapshot.snapshots(summaries)

        try ReplayCorpus.withTemporaryFile(Self.mixedDLTPcapngBytes, ext: "pcapng") { url in
            let result = try SavedCaptureStreamLoader(contentsOf: url).load()
            #expect(result.format == .pcapng)
            #expect(result.metadata.totalFrames == 3)
            #expect(result.metadata.linkTypeCounts == [
                CaptureLinkTypeCount(linkType: LinkType.ethernet, frameCount: 1),
                CaptureLinkTypeCount(linkType: LinkType.linuxSLL, frameCount: 1),
                CaptureLinkTypeCount(linkType: LinkType.linuxSLL2, frameCount: 1),
            ])
            #expect(result.metadata.hasMixedLinkTypes)
            // Both cooked DLTs decode to a link layer, so they add no coverage caveat.
            #expect(result.metadata.undecodableLinkLayerFrameCount == 0)
            #expect(Set(result.evidence.values.map(\.linkType)) == [
                LinkType.ethernet, LinkType.linuxSLL, LinkType.linuxSLL2,
            ])
            let saved = try savedRestoredSnapshots(from: url)
            #expect(saved == batch)
        }

        // Writing the same frames back out and re-reading them preserves each
        // frame's bytes and its own link type, and folds the identical sessions.
        let written = try PcapngWriter.data(defaultLinkType: LinkType.ethernet, frames: frames)
        try ReplayCorpus.withTemporaryFile([UInt8](written), ext: "pcapng") { url in
            let reread = try PcapngReader.read(contentsOf: url)
            #expect(reread.frames.map(\.bytes) == entries.map(\.bytes))
            #expect(reread.frames.map(\.linkType) == [
                LinkType.ethernet, LinkType.linuxSLL, LinkType.linuxSLL2,
            ])
            let saved = try savedRestoredSnapshots(from: url)
            #expect(saved == batch)
        }
    }

    // MARK: Private

    /// One generated frame plus the link type its interface declares.
    private struct MixedFrame {
        let bytes: [UInt8]
        let linkType: UInt32
    }

    private static let request = Array("GET /health HTTP/1.1\r\nHost: sll.example\r\n\r\n".utf8)
    private static let response = Array("HTTP/1.1 200 OK\r\nContent-Length: 0\r\n\r\n".utf8)

    /// The followed conversation carried inside the cooked frames.
    private static let tuple = FiveTuple(
        proto: .tcp,
        source: IPEndpoint(ip: LinuxCookedFixture.client, port: 51_000),
        destination: IPEndpoint(ip: LinuxCookedFixture.server, port: 443)
    )

    /// One frame per link type, each a distinct HTTP conversation so the folded
    /// sessions stay one-to-one with the DLTs that decoded them.
    private static var mixedDLTEntries: [MixedFrame] {
        let ethernet = httpFrame(host: "eth.example", src: "198.51.100.21", dst: "203.0.113.71", srcPort: 52_001)
        let sll = LinuxCookedFixture.sll(
            protocolNumber: 0x0800,
            payload: Array(httpFrame(
                host: "sll.example", src: "198.51.100.22", dst: "203.0.113.72", srcPort: 52_002
            ).dropFirst(14))
        )
        let sll2 = LinuxCookedFixture.sll2(
            protocolNumber: 0x0800,
            payload: Array(httpFrame(
                host: "sll2.example", src: "198.51.100.23", dst: "203.0.113.73", srcPort: 52_003
            ).dropFirst(14))
        )
        return [
            MixedFrame(bytes: ethernet, linkType: LinkType.ethernet),
            MixedFrame(bytes: sll, linkType: LinkType.linuxSLL),
            MixedFrame(bytes: sll2, linkType: LinkType.linuxSLL2),
        ]
    }

    private static var mixedDLTPcapngBytes: [UInt8] {
        let entries = mixedDLTEntries
        var file = PcapngFixture.sectionHeader(little: true)
        for entry in entries {
            file += PcapngFixture.interfaceDescription(little: true, linkType: UInt16(entry.linkType))
        }
        for (index, entry) in entries.enumerated() {
            file += PcapngFixture.enhancedPacket(
                little: true,
                interfaceID: UInt32(index),
                ticks: UInt64(1_700_000_000 + index + 1) * 1_000_000,
                captured: entry.bytes
            )
        }
        return file
    }

    /// Four ordered cooked frames: two TCP segments of one five-tuple, a DNS query
    /// and an ARP request — three sessions in all.
    private static func conversation(_ version: LinuxCookedHeader.Version) -> [ReplayCorpus.Frame] {
        let payloads: [(protocolNumber: UInt16, bytes: [UInt8])] = [
            (0x0800, tcpPayload(fromClient: true, sequence: 1_000, bytes: request)),
            (0x0800, tcpPayload(fromClient: false, sequence: 5_000, bytes: response)),
            (0x0800, LinuxCookedFixture.ipv4DNSPayload()),
            (0x0806, LinuxCookedFixture.arpPayload()),
        ]
        return payloads.enumerated().map { index, payload in
            ReplayCorpus.Frame(
                bytes: LinuxCookedFixture.frame(
                    version, protocolNumber: payload.protocolNumber, payload: payload.bytes
                ),
                offsetSeconds: index + 1,
                linkType: LinuxCookedFixture.linkType(version)
            )
        }
    }

    /// The same ordered frames as `CapturedFrame`s with no intrinsic link type, so
    /// the batch fold resolves them through the source default — exactly what the
    /// saved single-DLT file does.
    private static func capturedFrames(_ version: LinuxCookedHeader.Version) -> [CapturedFrame] {
        conversation(version).map { frame in
            CapturedFrame(
                bytes: frame.bytes, timestamp: frame.timestamp, originalLength: frame.bytes.count
            )
        }
    }

    private static func classicBytes(_ version: LinuxCookedHeader.Version) -> [UInt8] {
        ReplayCorpus.classicPcapBytes(
            conversation(version), variant: .littleMicro, linkType: LinuxCookedFixture.linkType(version)
        )
    }

    private static func pcapngBytes(_ version: LinuxCookedHeader.Version) -> [UInt8] {
        var file = PcapngFixture.sectionHeader(little: true)
        file += PcapngFixture.interfaceDescription(
            little: true, linkType: UInt16(LinuxCookedFixture.linkType(version))
        )
        for frame in conversation(version) {
            file += PcapngFixture.enhancedPacket(
                little: true,
                interfaceID: 0,
                ticks: UInt64(1_700_000_000 + frame.offsetSeconds) * 1_000_000,
                captured: frame.bytes
            )
        }
        return file
    }

    /// One TCP segment of the followed conversation, with its Ethernet header
    /// removed so a cooked header can carry it.
    private static func tcpPayload(fromClient: Bool, sequence: UInt32, bytes: [UInt8]) -> [UInt8] {
        Array(PacketBuilder.ethernetIPv4(
            proto: 6,
            src: fromClient ? LinuxCookedFixture.client : LinuxCookedFixture.server,
            dst: fromClient ? LinuxCookedFixture.server : LinuxCookedFixture.client,
            payload: PacketBuilder.tcp(
                srcPort: fromClient ? 51_000 : 443,
                dstPort: fromClient ? 443 : 51_000,
                flags: 0x18,
                payload: bytes,
                sequence: sequence
            )
        ).dropFirst(14))
    }

    private static func httpFrame(host: String, src: String, dst: String, srcPort: UInt16) -> [UInt8] {
        PacketBuilder.httpRequestFrame(host: host, path: "/health", src: src, dst: dst, srcPort: srcPort)
    }

    /// Saved summaries hold no raw representative bytes; restore them exactly
    /// through the evidence reader so the comparison covers them too.
    private func savedRestoredSnapshots(from url: URL) throws -> [SessionSnapshot] {
        let result = try SavedCaptureStreamLoader(contentsOf: url).load()
        var sessions = result.sessions
        for index in sessions.indices {
            let reference = try #require(result.evidence[sessions[index].id])
            sessions[index].representativeBytes = try CaptureEvidenceReader.read(reference, from: url)
        }
        return SessionSnapshot.snapshots(sessions)
    }
}
