import Foundation
import Testing
@testable import Tracexy

// MARK: - DatagramEvidenceTableTests

/// Direct, adversarial coverage of the bounded DNS/ICMP datagram evidence fold plus
/// the `SessionAccumulator` wiring that feeds it. Every fixture is generated by
/// `PacketBuilder` from reserved documentation addresses; no capture is read and no
/// name/answer/body string is ever asserted to appear in the evidence — the fold
/// retains only typed wire facts.
struct DatagramEvidenceTableTests {
    // MARK: Internal

    // MARK: Kind mapping and canonical direction/order

    @Test
    func udpDNSMapsToTypedFactsInCanonicalDirectionAndOrder() throws {
        var table = DatagramEvidenceTable()
        let query = decode(PacketBuilder.dnsQueryFrame(
            name: "one.example", src: client, dst: dnsServer, srcPort: 54_000
        ))
        let response = decode(PacketBuilder.dnsResponseFrame(
            name: "one.example", answers: [server], src: dnsServer, dst: client, dstPort: 54_000
        ))
        table.offer(query, provenance: provenance(1))
        table.offer(response, provenance: provenance(2))

        let snapshot = table.snapshot()
        #expect(snapshot.summaries.count == 1)
        let summary = try #require(snapshot.summaries.first)
        #expect(summary.observations.count == 2)
        // First-seen accepted order preserved.
        #expect(summary.observations.map(\.provenance.ordinal.rawValue) == [1, 2])
        // Direction derives only from source vs the canonical tuple: query is aToB
        // (client is the canonically-smaller endpoint here), response is bToA.
        #expect(summary.observations[0].direction == .aToB)
        #expect(summary.observations[1].direction == .bToA)
        // Privacy-by-type: the retained kind is exactly the decoder's typed DNS
        // facts — never the queried name or any answer value.
        #expect(try summary.observations[0].kind == .dns(#require(query.dnsFacts)))
        #expect(try summary.sessionID == SessionBuilder.sessionID(for: #require(query.fiveTuple)))
        #expect(snapshot.retainedObservationCount == 2)
        #expect(snapshot.excludedTCPDNSFactCount == 0)
    }

    @Test
    func icmpV4AndV6MapToTypedFamilyFacts() throws {
        var table = DatagramEvidenceTable()
        let v4 = decode(PacketBuilder.icmpEchoRequestFrame(src: client, dst: server))
        let v6 = decode(PacketBuilder.ethernetIPv6(
            nextHeader: 58, src: v6Client, dst: v6Server, payload: [128, 0, 0, 0, 0, 1, 0, 1]
        ))
        table.offer(v4, provenance: provenance(1))
        table.offer(v6, provenance: provenance(2))

        let snapshot = table.snapshot()
        #expect(snapshot.summaries.count == 2)
        #expect(snapshot.retainedObservationCount == 2)
        #expect(try snapshot.summaries[0].observations[0].kind == .icmp(#require(v4.icmpFacts)))
        #expect(try snapshot.summaries[1].observations[0].kind == .icmp(#require(v6.icmpFacts)))
        // The family came from the known IP protocol, not the body.
        if case let .icmp(facts) = snapshot.summaries[1].observations[0].kind {
            #expect(facts.family == .ipv6)
        } else {
            Issue.record("expected an ICMPv6 kind")
        }
    }

    // MARK: Exclusions

    @Test
    func tuplelessAndNonDatagramFramesAreIgnored() {
        var table = DatagramEvidenceTable()
        // ARP carries no DNS/ICMP facts; a TLS-over-TCP frame is a datagram-free
        // TCP flow — neither is retained and neither is a TCP-DNS exclusion.
        table.offer(
            decode(PacketBuilder.arpRequestFrame(senderIP: client, targetIP: server)),
            provenance: provenance(1)
        )
        table.offer(
            decode(PacketBuilder.tlsClientHelloFrame(sni: "x.example", src: client, dst: server, srcPort: 40_000)),
            provenance: provenance(2)
        )
        #expect(table.snapshot() == .empty)
    }

    @Test
    func tcpDNSFactsAreExcludedCountedNeverRetained() {
        var table = DatagramEvidenceTable()
        let tcpDNS = decode(tcpDNSFrame(name: "tcp.example", src: client, dst: server, srcPort: 40_100))
        // A complete per-frame TCP-DNS fact: decoded facts exist, but on a TCP flow.
        #expect(tcpDNS.dnsFacts != nil)
        #expect(tcpDNS.transport == .tcp)
        table.offer(tcpDNS, provenance: provenance(1))

        let snapshot = table.snapshot()
        #expect(snapshot.summaries.isEmpty)
        #expect(snapshot.retainedObservationCount == 0)
        #expect(snapshot.excludedTCPDNSFactCount == 1)
    }

    // MARK: Sticky loss and snap truncation

    @Test
    func lossKnowledgeMergesStickilyAcrossFrames() {
        var table = DatagramEvidenceTable()
        let query = decode(PacketBuilder.dnsQueryFrame(name: "a.example", src: client, dst: dnsServer))
        let response = decode(PacketBuilder.dnsResponseFrame(
            name: "a.example", answers: [server], src: dnsServer, dst: client
        ))
        table.offer(query, provenance: provenance(1), loss: .noLossReported)
        table.offer(response, provenance: provenance(2), loss: .lossReported)
        // A later weaker report never downgrades the sticky knowledge.
        table.offer(
            decode(PacketBuilder.dnsQueryFrame(name: "a.example", src: client, dst: dnsServer)),
            provenance: provenance(3), loss: .unknown
        )
        #expect(table.snapshot().summaries[0].lossKnowledge == .lossReported)
    }

    @Test
    func snapLengthTruncationIsObservedFromProvenance() {
        var table = DatagramEvidenceTable()
        let query = decode(PacketBuilder.dnsQueryFrame(name: "t.example", src: client, dst: dnsServer))
        // Original on-wire length exceeds captured length → truncation observed.
        table.offer(query, provenance: SessionFrameProvenance(
            ordinal: FrameOrdinal(1), timestamp: instant(1),
            capturedLength: query.rawBytes.count, originalLength: query.rawBytes.count + 200,
            linkType: LinkType.ethernet
        ))
        #expect(table.snapshot().summaries[0].snapLengthTruncationObserved)
    }

    // MARK: Bounds — exact occurrence omissions

    @Test
    func perSummaryCapRetainsBoundAndCountsExactOmissions() {
        var table = DatagramEvidenceTable(configuration: .init(maxObservationsPerSummary: 2))
        for ordinal in 1 ... 5 {
            table.offer(
                decode(PacketBuilder.dnsQueryFrame(name: "c.example", src: client, dst: dnsServer)),
                provenance: provenance(UInt64(ordinal))
            )
        }
        let snapshot = table.snapshot()
        #expect(snapshot.summaries[0].observations.count == 2)
        #expect(snapshot.summaries[0].omittedObservationCount == 3)
        #expect(snapshot.omittedObservationCount == 3)
        #expect(snapshot.retainedObservationCount == 2)
        #expect(snapshot.capacityReached)
    }

    @Test
    func globalObservationCapBoundsAcrossSummaries() {
        var table = DatagramEvidenceTable(configuration: .init(maxTotalObservations: 1))
        table.offer(
            decode(PacketBuilder.dnsQueryFrame(name: "g1.example", src: client, dst: dnsServer)),
            provenance: provenance(1)
        )
        table.offer(
            decode(PacketBuilder.icmpEchoRequestFrame(src: client, dst: server)),
            provenance: provenance(2)
        )
        let snapshot = table.snapshot()
        #expect(snapshot.retainedObservationCount == 1)
        #expect(snapshot.omittedObservationCount == 1)
        // The second flow still gets a summary (a known flow), but no observation.
        #expect(snapshot.summaries.count == 2)
        #expect(snapshot.capacityReached)
    }

    @Test
    func summaryCapDropsNewFlowAndCountsOnePerOccurrence() {
        var table = DatagramEvidenceTable(configuration: .init(maxSummaries: 1))
        table.offer(
            decode(PacketBuilder.dnsQueryFrame(name: "s1.example", src: client, dst: dnsServer)),
            provenance: provenance(1)
        )
        // A second, distinct flow after the summary cap: not retained at all; each
        // occurrence is one global omitted observation.
        table.offer(decode(PacketBuilder.icmpEchoRequestFrame(src: client, dst: server)), provenance: provenance(2))
        table.offer(decode(PacketBuilder.icmpEchoRequestFrame(src: client, dst: server)), provenance: provenance(3))

        let snapshot = table.snapshot()
        #expect(snapshot.summaries.count == 1)
        #expect(snapshot.retainedObservationCount == 1)
        #expect(snapshot.omittedObservationCount == 2)
        #expect(snapshot.capacityReached)
    }

    // MARK: Saturation helper and empty

    @Test
    func saturatingAddSaturatesAndReportsOverflow() {
        #expect(DatagramEvidenceTable.saturatingAdd(1, 2) == (3, false))
        #expect(DatagramEvidenceTable.saturatingAdd(UInt64.max, 1) == (UInt64.max, true))
        #expect(DatagramEvidenceTable.saturatingAdd(UInt64.max - 1, 1) == (UInt64.max, false))
    }

    @Test
    func freshTableEqualsEmptySnapshot() {
        let table = DatagramEvidenceTable()
        #expect(table.snapshot() == .empty)
        #expect(DatagramEvidenceTable.Snapshot.empty.summaries.isEmpty)
        #expect(DatagramEvidenceTable.Snapshot.empty.retainedObservationCount == 0)
    }

    // MARK: SessionAccumulator wiring

    @Test
    func acceptedOrdinalsAdvanceAcrossInterveningTuplelessAndTCPFrames() throws {
        var accumulator = SessionAccumulator()
        // ordinal 1: ICMP (retained), 2: ARP (ignored), 3: TLS/TCP (ignored),
        // 4: UDP DNS (retained). Ordinals are assigned per accepted frame regardless
        // of retention, so the DNS observation must land at ordinal 4.
        add(&accumulator, PacketBuilder.icmpEchoRequestFrame(src: client, dst: server))
        add(&accumulator, PacketBuilder.arpRequestFrame(senderIP: client, targetIP: server))
        add(
            &accumulator,
            PacketBuilder.tlsClientHelloFrame(sni: "y.example", src: client, dst: server, srcPort: 41_000)
        )
        add(&accumulator, PacketBuilder.dnsQueryFrame(name: "four.example", src: client, dst: dnsServer))

        let evidence = accumulator.foldSnapshot().datagramEvidence
        #expect(evidence.retainedObservationCount == 2)
        let icmp = try #require(evidence.summaries.first { summary in
            summary.observations.contains {
                if case .icmp = $0.kind {
                    true
                } else {
                    false
                }
            }
        })
        let dns = try #require(evidence.summaries.first { summary in
            summary.observations.contains {
                if case .dns = $0.kind {
                    true
                } else {
                    false
                }
            }
        })
        #expect(icmp.observations[0].provenance.ordinal == FrameOrdinal(1))
        #expect(dns.observations[0].provenance.ordinal == FrameOrdinal(4))
    }

    @Test
    func reassembledTCPDNSIsExcludedCountedAndNeverRetained() {
        var accumulator = SessionAccumulator()
        // A DNS message split across two TCP/53 segments of one five-tuple: the
        // connection probe reassembles it, but the datagram table excludes-counts the
        // fact rather than retaining it.
        let message = PacketBuilder.dnsQuery(name: "split.example")
        let payload = [UInt8(message.count >> 8), UInt8(message.count & 0xFF)] + message
        let cut = 5
        add(&accumulator, tcpSegment(
            payload: Array(payload[..<cut]), sequence: 1, src: client, dst: server, srcPort: 40_200, dstPort: 53
        ))
        add(&accumulator, tcpSegment(
            payload: Array(payload[cut...]), sequence: 1 + UInt32(cut),
            src: client, dst: server, srcPort: 40_200, dstPort: 53
        ))

        let fold = accumulator.foldSnapshot()
        // No DNS observation was retained for the TCP flow.
        #expect(!fold.datagramEvidence.summaries.contains { summary in
            summary.observations.contains {
                if case .dns = $0.kind {
                    true
                } else {
                    false
                }
            }
        })
        #expect(fold.datagramEvidence.excludedTCPDNSFactCount >= 1)
        // The reassembly path genuinely classified DNS (proving the exclusion covers
        // a reassembled fact, not only a per-frame one).
        #expect(fold.connections.summaries.contains { summary in
            summary.events.contains { $0.applicationKind == .dns }
        })
    }

    @Test
    func resetClearsDatagramEvidence() {
        var accumulator = SessionAccumulator()
        add(&accumulator, PacketBuilder.dnsQueryFrame(name: "r.example", src: client, dst: dnsServer))
        #expect(!accumulator.foldSnapshot().datagramEvidence.summaries.isEmpty)
        accumulator.reset()
        #expect(accumulator.foldSnapshot().datagramEvidence == .empty)
    }

    // MARK: Private

    private let client = "198.51.100.10"
    private let server = "203.0.113.5"
    private let dnsServer = "203.0.113.53"
    private let v6Client: [UInt16] = [0x2001, 0x0DB8, 0, 0, 0, 0, 0, 0x0010]
    private let v6Server: [UInt16] = [0x2001, 0x0DB8, 0, 0, 0, 0, 0, 0x0053]

    private func instant(_ ordinal: UInt64) -> Date {
        Date(timeIntervalSince1970: 1_700_000_000 + Double(ordinal))
    }

    private func provenance(_ ordinal: UInt64) -> SessionFrameProvenance {
        SessionFrameProvenance(
            ordinal: FrameOrdinal(ordinal),
            timestamp: instant(ordinal),
            capturedLength: 0,
            originalLength: 0,
            linkType: LinkType.ethernet
        )
    }

    private func decode(_ bytes: [UInt8], linkType: UInt32 = LinkType.ethernet) -> DecodedPacket {
        var packet = PacketDecoder.decode(
            PacketBuffer(bytes), linkType: linkType, timestamp: instant(0), originalLength: bytes.count
        )
        packet.rawBytes = bytes
        return packet
    }

    /// Fold one frame's bytes through the common accumulator path with a nil-locator
    /// batch-style context, so ordinals are assigned exactly as batch/live do.
    private func add(_ accumulator: inout SessionAccumulator, _ bytes: [UInt8]) {
        let frame = CapturedFrame(bytes: bytes, timestamp: instant(0), originalLength: bytes.count)
        let packet = SessionBuilder.decodePacket(frame, linkType: LinkType.ethernet)
        accumulator.add(packet, context: SessionBuilder.frameContext(for: frame, linkType: LinkType.ethernet))
    }

    /// An Ethernet+IPv4+TCP/53 segment carrying a length-prefixed DNS message.
    private func tcpDNSFrame(name: String, src: String, dst: String, srcPort: UInt16) -> [UInt8] {
        let message = PacketBuilder.dnsQuery(name: name)
        let payload = [UInt8(message.count >> 8), UInt8(message.count & 0xFF)] + message
        return tcpSegment(payload: payload, sequence: 1, src: src, dst: dst, srcPort: srcPort, dstPort: 53)
    }

    private func tcpSegment(
        payload: [UInt8],
        sequence: UInt32,
        src: String,
        dst: String,
        srcPort: UInt16,
        dstPort: UInt16
    )
        -> [UInt8]
    {
        PacketBuilder.ethernetIPv4(
            proto: 6, src: src, dst: dst,
            payload: PacketBuilder.tcp(
                srcPort: srcPort, dstPort: dstPort, flags: 0x18, payload: payload, sequence: sequence
            )
        )
    }
}
