import Foundation
import Testing
@testable import Tracexy

// MARK: - Byte helpers

private func be16(_ value: UInt16) -> [UInt8] {
    [UInt8(value >> 8), UInt8(value & 0xFF)]
}

/// Wraps a raw TLS record body into record bytes (header + body).
private func tlsRecordBytes(contentType: UInt8, version: UInt16 = 0x0303, body: [UInt8]) -> [UInt8] {
    [contentType] + be16(version) + be16(UInt16(body.count)) + body
}

// MARK: - TLSEvidenceTableTests

/// Direct, adversarial coverage of the bounded TLS record evidence fold plus the
/// `SessionAccumulator` wiring that feeds it. Every fixture is generated by
/// `PacketBuilder` from reserved documentation addresses; no capture is read and no
/// SNI/host/certificate string is ever asserted to appear in the evidence — the fold
/// retains only typed `TLSRecordFact` wire facts with exact direct-frame provenance.
struct TLSEvidenceTableTests {
    // MARK: Internal

    // MARK: Direct record retention: order, index, direction, provenance

    @Test
    func directRecordsRetainInOrderWithIndexAndCanonicalDirection() throws {
        var table = TLSEvidenceTable()
        // Two coalesced records in one client→server frame, then one server→client
        // record of the same canonical tuple.
        let clientFrame = tcpTLSFrame(
            payload: tlsRecordBytes(contentType: 22, body: [0x01, 0x02])
                + tlsRecordBytes(contentType: 23, body: [0xAA]),
            src: client, dst: server, srcPort: 44_000
        )
        let serverFrame = tcpTLSFrame(
            payload: tlsRecordBytes(contentType: 22, body: [0x02, 0x00, 0x00, 0x00]),
            src: server, dst: client, srcPort: 443, dstPort: 44_000
        )
        let clientPacket = decode(clientFrame)
        let serverPacket = decode(serverFrame)
        table.offer(clientPacket, application: nil, provenance: provenance(1))
        table.offer(serverPacket, application: nil, provenance: provenance(2))

        let snapshot = table.snapshot()
        #expect(snapshot.summaries.count == 1)
        let summary = try #require(snapshot.summaries.first)
        #expect(summary.observations.count == 3)
        // Within-frame record index is zero-based and ordered; frame order is preserved.
        #expect(summary.observations.map(\.recordIndex) == [0, 1, 0])
        #expect(summary.observations.map(\.provenance.ordinal.rawValue) == [1, 1, 2])
        // The two directions are opposite (canonical aToB vs bToA), and same-direction
        // records within one frame share a direction.
        #expect(summary.observations[0].direction == summary.observations[1].direction)
        #expect(summary.observations[0].direction != summary.observations[2].direction)
        #expect(Set(summary.observations.map(\.direction)).count == 2)
        // Privacy-by-type: the retained fact is exactly the decoder's typed record fact.
        #expect(summary.observations[0].fact == clientPacket.tlsRecords[0])
        #expect(summary.observations[1].fact == clientPacket.tlsRecords[1])
        #expect(try summary.sessionID == SessionBuilder.sessionID(for: #require(clientPacket.fiveTuple)))
        #expect(snapshot.retainedObservationCount == 3)
        #expect(snapshot.excludedReassembledRecordCount == 0)
        #expect(!snapshot.capacityReached)
    }

    @Test
    func nonTLSAndTuplelessFramesAreIgnored() {
        var table = TLSEvidenceTable()
        // ARP carries no tuple; a bare TCP SYN (no payload) carries no TLS record.
        table.offer(
            decode(PacketBuilder.arpRequestFrame(senderIP: client, targetIP: server)),
            application: nil,
            provenance: provenance(1)
        )
        table.offer(
            decode(PacketBuilder.tcpSynFrame(src: client, dst: server, srcPort: 40_000, dstPort: 443)),
            application: nil,
            provenance: provenance(2)
        )
        #expect(table.snapshot() == .empty)
    }

    // MARK: Decoder truncation (direct 32-record cap)

    @Test
    func directDecoderTruncationIsCountedPerFrameWithoutInventingRecords() throws {
        var table = TLSEvidenceTable()
        let unit = tlsRecordBytes(contentType: 23, body: [0xAB])
        let packet = decode(tcpTLSFrame(
            payload: Array(repeating: unit, count: 33).flatMap { $0 }, src: client, dst: server, srcPort: 44_100
        ))
        // The decoder capped the direct walk at 32 and flagged truncation.
        #expect(packet.tlsRecords.count == 32)
        #expect(packet.tlsRecordsTruncated)
        table.offer(packet, application: nil, provenance: provenance(1))

        let snapshot = table.snapshot()
        // Exactly the 32 captured records are retained; the unknown remainder is a
        // per-frame lower-bound coverage count, never a fabricated record total.
        #expect(snapshot.retainedObservationCount == 32)
        #expect(snapshot.decoderTruncatedFrameCount == 1)
        #expect(try #require(snapshot.summaries.first).decoderTruncatedFrameCount == 1)
        #expect(snapshot.excludedReassembledRecordCount == 0)
    }

    // MARK: Reassembled exclusion and recovered truncation (table level)

    @Test
    func reassembledRecordsAreExcludedCountedNeverRetained() throws {
        var table = TLSEvidenceTable()
        // A carrier frame with a tuple but no direct TLS record (a bare payload-less
        // segment), plus a reassembled handoff carrying two recovered records and a
        // recovered truncation indicator.
        let carrier = decode(PacketBuilder.tcpSynFrame(src: client, dst: server, srcPort: 44_200, dstPort: 443))
        #expect(carrier.tlsRecords.isEmpty)
        table.offer(carrier, application: reassembled(records: 2, truncated: true), provenance: provenance(1))

        let snapshot = table.snapshot()
        // No record was retained or cited; the recovered records/truncation are counted
        // as truthful coverage against the flow's summary and globally.
        #expect(snapshot.retainedObservationCount == 0)
        #expect(snapshot.excludedReassembledRecordCount == 2)
        #expect(snapshot.recoveredTruncationIndicatorCount == 1)
        let summary = try #require(snapshot.summaries.first)
        #expect(summary.observations.isEmpty)
        #expect(summary.excludedReassembledRecordCount == 2)
        #expect(summary.recoveredTruncationIndicatorCount == 1)
    }

    @Test
    func directFrameSuppressesReassembledExclusionToAvoidDoubleCount() {
        var table = TLSEvidenceTable()
        // A complete single-frame record has direct facts; the same frame's reassembled
        // handoff also carries records, but must not be excluded-counted.
        let packet = decode(tcpTLSFrame(
            payload: tlsRecordBytes(contentType: 22, body: [0x01, 0x02, 0x03]), src: client, dst: server,
            srcPort: 44_300
        ))
        #expect(!packet.tlsRecords.isEmpty)
        table.offer(packet, application: reassembled(records: 5, truncated: true), provenance: provenance(1))

        let snapshot = table.snapshot()
        #expect(snapshot.retainedObservationCount == packet.tlsRecords.count)
        #expect(snapshot.excludedReassembledRecordCount == 0)
        #expect(snapshot.recoveredTruncationIndicatorCount == 0)
    }

    // MARK: Sticky loss and snap truncation

    @Test
    func lossKnowledgeMergesStickilyAndSnapTruncationIsObserved() throws {
        var table = TLSEvidenceTable()
        let record = tlsRecordBytes(contentType: 23, body: [0x00])
        let first = decode(tcpTLSFrame(payload: record, src: client, dst: server, srcPort: 44_400))
        table.offer(first, application: nil, provenance: SessionFrameProvenance(
            ordinal: FrameOrdinal(1), timestamp: instant(1),
            capturedLength: first.rawBytes.count, originalLength: first.rawBytes.count + 100,
            linkType: LinkType.ethernet
        ), loss: .lossReported)
        // A later weaker report never downgrades the sticky knowledge.
        table.offer(
            decode(tcpTLSFrame(payload: record, src: client, dst: server, srcPort: 44_400)),
            application: nil, provenance: provenance(2), loss: .unknown
        )
        let summary = try #require(table.snapshot().summaries.first)
        #expect(summary.lossKnowledge == .lossReported)
        #expect(summary.snapLengthTruncationObserved)
    }

    @Test
    func lossAndSnapMetadataSurviveOmittedAndExcludedFacts() throws {
        var table = TLSEvidenceTable(configuration: .init(maxObservationsPerSummary: 1))
        let record = tlsRecordBytes(contentType: 23, body: [0x00])
        let retained = decode(tcpTLSFrame(payload: record, src: client, dst: server, srcPort: 44_401))
        table.offer(retained, application: nil, provenance: provenance(1))

        let omitted = decode(tcpTLSFrame(payload: record, src: client, dst: server, srcPort: 44_401))
        table.offer(omitted, application: nil, provenance: SessionFrameProvenance(
            ordinal: FrameOrdinal(2), timestamp: instant(2),
            capturedLength: omitted.rawBytes.count, originalLength: omitted.rawBytes.count + 1,
            linkType: LinkType.ethernet
        ), loss: .lossReported)

        let excludedCarrier = decode(PacketBuilder.tcpSynFrame(
            src: client, dst: otherServer, srcPort: 44_402, dstPort: 443
        ))
        table.offer(
            excludedCarrier,
            application: reassembled(records: 1, truncated: false),
            provenance:
            SessionFrameProvenance(
                ordinal: FrameOrdinal(3), timestamp: instant(3),
                capturedLength: excludedCarrier.rawBytes.count,
                originalLength: excludedCarrier.rawBytes.count + 1,
                linkType: LinkType.ethernet
            ),
            loss: .lossReported
        )

        let snapshot = table.snapshot()
        let omittedSummary = try #require(snapshot.summaries.first {
            $0.tuple.a.port == 44_401 || $0.tuple.b.port == 44_401
        })
        #expect(omittedSummary.omittedObservationCount == 1)
        #expect(omittedSummary.lossKnowledge == .lossReported)
        #expect(omittedSummary.snapLengthTruncationObserved)

        let excludedSummary = try #require(snapshot.summaries.first {
            $0.tuple.a.port == 44_402 || $0.tuple.b.port == 44_402
        })
        #expect(excludedSummary.observations.isEmpty)
        #expect(excludedSummary.excludedReassembledRecordCount == 1)
        #expect(excludedSummary.lossKnowledge == .lossReported)
        #expect(excludedSummary.snapLengthTruncationObserved)
    }

    // MARK: Bounds — exact occurrence omissions

    @Test
    func perSummaryCapRetainsBoundAndCountsExactOmissions() throws {
        var table = TLSEvidenceTable(configuration: .init(maxObservationsPerSummary: 2))
        for ordinal in 1 ... 5 {
            table.offer(
                decode(tcpTLSFrame(
                    payload: tlsRecordBytes(contentType: 23, body: [0x01]),
                    src: client,
                    dst: server,
                    srcPort: 44_500
                )),
                application: nil, provenance: provenance(UInt64(ordinal))
            )
        }
        let snapshot = table.snapshot()
        let summary = try #require(snapshot.summaries.first)
        #expect(summary.observations.count == 2)
        #expect(summary.omittedObservationCount == 3)
        #expect(snapshot.omittedObservationCount == 3)
        #expect(snapshot.retainedObservationCount == 2)
        #expect(snapshot.capacityReached)
    }

    @Test
    func globalObservationCapBoundsAcrossSummaries() {
        var table = TLSEvidenceTable(configuration: .init(maxTotalObservations: 1))
        table.offer(
            decode(tcpTLSFrame(
                payload: tlsRecordBytes(contentType: 22, body: [0x00]),
                src: client,
                dst: server,
                srcPort: 44_600
            )),
            application: nil, provenance: provenance(1)
        )
        table.offer(
            decode(tcpTLSFrame(
                payload: tlsRecordBytes(contentType: 22, body: [0x00]),
                src: client,
                dst: otherServer,
                srcPort: 44_601
            )),
            application: nil, provenance: provenance(2)
        )
        let snapshot = table.snapshot()
        #expect(snapshot.retainedObservationCount == 1)
        #expect(snapshot.omittedObservationCount == 1)
        // The second flow still gets a summary (a known flow), but no observation.
        #expect(snapshot.summaries.count == 2)
        #expect(snapshot.capacityReached)
    }

    @Test
    func summaryCapDropsNewFlowAndCountsEveryOccurrenceGlobally() {
        var table = TLSEvidenceTable(configuration: .init(maxSummaries: 1))
        table.offer(
            decode(tcpTLSFrame(
                payload: tlsRecordBytes(contentType: 22, body: [0x00]),
                src: client,
                dst: server,
                srcPort: 44_700
            )),
            application: nil, provenance: provenance(1)
        )
        // A second, distinct flow after the summary cap: not retained; each direct
        // record occurrence is one global omission, and recovered coverage still counts.
        let carrier = decode(PacketBuilder.tcpSynFrame(src: client, dst: otherServer, srcPort: 44_701, dstPort: 443))
        table.offer(carrier, application: reassembled(records: 3, truncated: true), provenance: provenance(2))
        table.offer(
            decode(tcpTLSFrame(
                payload: tlsRecordBytes(contentType: 22, body: [0x00])
                    + tlsRecordBytes(contentType: 23, body: [0x01]),
                src: client,
                dst: otherServer,
                srcPort: 44_701
            )),
            application: nil, provenance: provenance(3)
        )
        let snapshot = table.snapshot()
        #expect(snapshot.summaries.count == 1)
        #expect(snapshot.retainedObservationCount == 1)
        #expect(snapshot.omittedObservationCount == 2) // two direct records on the dropped flow
        #expect(snapshot.excludedReassembledRecordCount == 3)
        #expect(snapshot.recoveredTruncationIndicatorCount == 1)
        #expect(snapshot.capacityReached)
    }

    // MARK: Saturation helper, empty, determinism

    @Test
    func saturatingAddSaturatesAndReportsOverflow() {
        #expect(TLSEvidenceTable.saturatingAdd(1, 2) == (3, false))
        #expect(TLSEvidenceTable.saturatingAdd(UInt64.max, 1) == (UInt64.max, true))
        #expect(TLSEvidenceTable.saturatingAdd(UInt64.max - 1, 1) == (UInt64.max, false))
    }

    @Test
    func freshTableEqualsEmptySnapshotAndRepeatedSnapshotsAreDeterministic() {
        var table = TLSEvidenceTable()
        #expect(table.snapshot() == .empty)
        table.offer(
            decode(tcpTLSFrame(
                payload: tlsRecordBytes(contentType: 22, body: [0x01, 0x02]),
                src: client,
                dst: server,
                srcPort: 44_800
            )),
            application: nil, provenance: provenance(1)
        )
        let first = table.snapshot()
        let second = table.snapshot()
        #expect(first == second)
    }

    // MARK: SessionAccumulator wiring — direct + reassembled through the real fold

    @Test
    func splitClientHelloRetainsDirectFragmentAndExcludesRecoveredRecord() throws {
        var accumulator = SessionAccumulator()
        // A TLS ClientHello split across two TCP segments of one five-tuple: the first
        // segment carries a direct (fragment) record; the completing segment starts
        // mid-record, so its record is recovered only by the connection prefix probe.
        let hello = PacketBuilder.tlsClientHello(sni: "secure.example")
        let cut = hello.count / 2
        add(&accumulator, tcpTLSFrame(
            payload: Array(hello[..<cut]), src: client, dst: server, srcPort: 52_344, sequence: 1_000
        ))
        add(&accumulator, tcpTLSFrame(
            payload: Array(hello[cut...]), src: client, dst: server, srcPort: 52_344,
            sequence: 1_000 + UInt32(cut)
        ))

        let fold = accumulator.foldSnapshot()
        let tls = fold.tlsEvidence
        let summary = try #require(tls.summaries.first)
        // Exactly one direct observation was retained: the first segment's fragment
        // record (an honest incomplete body), never the recovered complete record.
        #expect(tls.retainedObservationCount == 1)
        #expect(summary.observations.count == 1)
        #expect(summary.observations[0].fact.bodyComplete == false)
        // The completing frame's recovered record is excluded-counted, not retained.
        #expect(tls.excludedReassembledRecordCount >= 1)
        // The reassembly path genuinely classified TLS (proving the exclusion covers a
        // recovered fact, not merely an absent one).
        #expect(fold.connections.summaries.contains { summary in
            summary.events.contains { $0.applicationKind == .tls }
        })
    }

    @Test
    func completeSingleFrameHelloIsNeverDoubleCountedThroughTheFold() {
        var accumulator = SessionAccumulator()
        add(&accumulator, PacketBuilder.tlsClientHelloFrame(
            sni: "solo.example", src: client, dst: server, srcPort: 40_900
        ))
        let fold = accumulator.foldSnapshot()
        let tls = fold.tlsEvidence
        #expect(tls.summaries.count == 1)
        #expect(tls.retainedObservationCount == 1)
        // The reassembled handoff exists and carries the same record, but the direct
        // frame suppresses excluding it — no double count.
        #expect(fold.connections.summaries.contains { summary in
            summary.events.contains { $0.applicationKind == .tls }
        })
        #expect(tls.excludedReassembledRecordCount == 0)
    }

    @Test
    func acceptedOrdinalsAdvanceAcrossInterveningNonTLSFrames() throws {
        var accumulator = SessionAccumulator()
        // ordinal 1: ARP (ignored), 2: UDP DNS (ignored by TLS), 3: TLS ClientHello.
        add(&accumulator, PacketBuilder.arpRequestFrame(senderIP: client, targetIP: server))
        add(&accumulator, PacketBuilder.dnsQueryFrame(name: "x.example", src: client, dst: server))
        add(
            &accumulator,
            PacketBuilder.tlsClientHelloFrame(sni: "z.example", src: client, dst: server, srcPort: 41_000)
        )

        let tls = accumulator.foldSnapshot().tlsEvidence
        let summary = try #require(tls.summaries.first)
        #expect(tls.summaries.count == 1)
        #expect(summary.observations[0].provenance.ordinal == FrameOrdinal(3))
    }

    @Test
    func resetClearsTLSEvidenceAndPreservesConfiguration() throws {
        var accumulator = SessionAccumulator(tlsConfiguration: .init(maxObservationsPerSummary: 2))
        for _ in 0 ..< 5 {
            add(&accumulator, PacketBuilder.tlsClientHelloFrame(
                sni: "keep.example", src: client, dst: server, srcPort: 41_100
            ))
        }
        // Injected tiny bound bit before reset (single flow, five ClientHellos → cap 2).
        #expect(accumulator.foldSnapshot().tlsEvidence.capacityReached)
        accumulator.reset()
        #expect(accumulator.foldSnapshot().tlsEvidence == .empty)
        // Configuration is preserved across reset: the same tiny cap still bites.
        for _ in 0 ..< 5 {
            add(&accumulator, PacketBuilder.tlsClientHelloFrame(
                sni: "keep.example", src: client, dst: server, srcPort: 41_100
            ))
        }
        let after = accumulator.foldSnapshot().tlsEvidence
        #expect(try #require(after.summaries.first).observations.count == 2)
    }

    // MARK: Private

    private let client = "198.51.100.10"
    private let server = "203.0.113.5"
    private let otherServer = "203.0.113.6"

    private func instant(_ ordinal: UInt64) -> Date {
        Date(timeIntervalSince1970: 1_700_000_000 + Double(ordinal))
    }

    private func provenance(_ ordinal: UInt64) -> SessionFrameProvenance {
        SessionFrameProvenance(
            ordinal: FrameOrdinal(ordinal),
            timestamp: instant(ordinal),
            capturedLength: 0,
            originalLength: 0,
            linkType: LinkType.ethernet
        )
    }

    private func decode(_ bytes: [UInt8], linkType: UInt32 = LinkType.ethernet) -> DecodedPacket {
        var packet = PacketDecoder.decode(
            PacketBuffer(bytes), linkType: linkType, timestamp: instant(0), originalLength: bytes.count
        )
        packet.rawBytes = bytes
        return packet
    }

    /// An Ethernet+IPv4+TCP frame carrying the given TLS payload (coalesced records).
    private func tcpTLSFrame(
        payload: [UInt8],
        src: String,
        dst: String,
        srcPort: UInt16,
        dstPort: UInt16 = 443,
        sequence: UInt32 = 1
    )
        -> [UInt8]
    {
        PacketBuilder.ethernetIPv4(
            proto: 6, src: src, dst: dst,
            payload: PacketBuilder.tcp(
                srcPort: srcPort, dstPort: dstPort, flags: 0x18, payload: payload, sequence: sequence
            )
        )
    }

    /// A synthetic reassembled application handoff carrying `records` neutral TLS record
    /// facts and an optional recovered truncation indicator — the shape the connection
    /// prefix probe produces, minted directly so a table test can pin exclusion.
    private func reassembled(records: Int, truncated: Bool) -> PacketDecoder.ReassembledTCPApplication {
        let fact = TLSRecordFact(
            contentType: 23, legacyRecordVersion: 0x0303, declaredBodyLength: 4,
            capturedBodyLength: 4, handshake: nil
        )
        return PacketDecoder.ReassembledTCPApplication(
            appProtocol: .tls, layers: [], sni: nil, dnsQuery: nil, dnsAnswers: [],
            dnsAnswersOmittedCount: 0, dnsFacts: nil,
            tlsRecords: Array(repeating: fact, count: records), tlsRecordsTruncated: truncated, isComplete: true
        )
    }

    /// Fold one frame's bytes through the common accumulator path with a nil-locator
    /// batch-style context, so ordinals are assigned exactly as batch/live do.
    private func add(_ accumulator: inout SessionAccumulator, _ bytes: [UInt8]) {
        let frame = CapturedFrame(bytes: bytes, timestamp: instant(0), originalLength: bytes.count)
        let packet = SessionBuilder.decodePacket(frame, linkType: LinkType.ethernet)
        accumulator.add(packet, context: SessionBuilder.frameContext(for: frame, linkType: LinkType.ethernet))
    }
}
