import Foundation
import Testing
@testable import Tracexy

// MARK: - ReplayRobustnessTests

/// Representative end-to-end robustness gates for the saved-open replay path:
/// malformed metadata, distinct truncated terminals with prior-session recovery,
/// evidence invalidation, cancellation, and named memory bounds (tail / activity /
/// progress) — plus a sparse multi-GiB early-start cancellation. These assert
/// typed outcomes and bounds rather than re-running every N1A/N1B unit permutation.
/// All bytes are generated by ``ReplayCorpus``.
struct ReplayRobustnessTests {
    // MARK: Internal

    // MARK: Malformed metadata is a controlled failure, never a trap

    @Test
    func malformedGlobalHeaderFailsClosed() throws {
        // A 24-byte all-zero header is neither pcapng nor a valid classic magic.
        try ReplayCorpus.withTemporaryFile([UInt8](repeating: 0, count: 24)) { url in
            #expect(throws: PacketError.self) {
                _ = try SavedCaptureStreamLoader(contentsOf: url)
            }
        }
    }

    @Test
    func impossibleRecordLengthsFailClosed() throws {
        // A record whose original length is below its captured length is corrupt
        // metadata and must throw rather than being normalised.
        var file = ReplayCorpus.classicPcapBytes([]) // global header only
        file += ReplayCorpus.classicRecordHeaderLE(seconds: 1, fraction: 0, inclLen: 10, origLen: 5)
        file += [UInt8](repeating: 0xAA, count: 10)
        try ReplayCorpus.withTemporaryFile(file) { url in
            let loader = try SavedCaptureStreamLoader(contentsOf: url)
            #expect(throws: PacketError.self) {
                _ = try loader.load()
            }
        }
    }

    @Test
    func overCapCapturedLengthFailsClosed() throws {
        try ReplayCorpus.withTemporaryFile(ReplayCorpus.classicPcapBytes(ReplayCorpus.conversation())) { url in
            let loader = try SavedCaptureStreamLoader(contentsOf: url, configuration: .init(maxCapturedLength: 4))
            #expect(throws: PacketError.self) {
                _ = try loader.load()
            }
        }
    }

    @Test
    func corruptPcapngTrailerFailsClosed() throws {
        let frame = Self.priorFrame
        var epb = PcapngFixture.enhancedPacket(
            little: true, interfaceID: 0, ticks: Self.microTicks(1), captured: frame.bytes
        )
        epb[epb.count - 1] ^= 0xFF // corrupt the trailing total-length word
        var file = PcapngFixture.sectionHeader(little: true)
        file += PcapngFixture.interfaceDescription(little: true, linkType: UInt16(LinkType.ethernet))
        file += epb
        try ReplayCorpus.withTemporaryFile(file, ext: "pcapng") { url in
            let loader = try SavedCaptureStreamLoader(contentsOf: url)
            #expect(throws: PacketError.self) {
                _ = try loader.load()
            }
        }
    }

    // MARK: Distinct truncated terminals, prior sessions recovered

    @Test
    func truncatedBodyPreservesPriorSessions() throws {
        var file = ReplayCorpus.classicPcapBytes([Self.priorFrame])
        // A complete record header declaring a payload that is not present.
        file += ReplayCorpus.classicRecordHeaderLE(seconds: 2, fraction: 0, inclLen: 64, origLen: 64)
        file += [0x01, 0x02, 0x03, 0x04]
        try ReplayCorpus.withTemporaryFile(file) { url in
            let result = try SavedCaptureStreamLoader(contentsOf: url).load()
            #expect(result.completeness == .incompleteTruncatedTail(.partialBody))
            #expect(result.totalFrames == 1)
            #expect(result.sessions.contains { $0.host == "prior.example" })
        }
    }

    @Test
    func truncatedHeaderIsADistinctTerminal() throws {
        var file = ReplayCorpus.classicPcapBytes([Self.priorFrame])
        file += [0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08] // < 16-byte record header
        try ReplayCorpus.withTemporaryFile(file) { url in
            let result = try SavedCaptureStreamLoader(contentsOf: url).load()
            #expect(result.completeness == .incompleteTruncatedTail(.partialHeader))
            #expect(result.totalFrames == 1)
            #expect(result.sessions.contains { $0.host == "prior.example" })
        }
    }

    // MARK: Evidence invalidation

    @Test
    func evidenceRejectsReplacementAndOverLimit() throws {
        try ReplayCorpus.withTemporaryFile(ReplayCorpus.classicPcapBytes([Self.priorFrame])) { url in
            let result = try SavedCaptureStreamLoader(contentsOf: url).load()
            let reference = try #require(result.evidence.values.first)
            #expect(try CaptureEvidenceReader.read(reference, from: url) == Self.priorFrame.bytes)

            // Over-limit captured length is rejected on bounds alone.
            #expect(throws: PacketError.self) {
                _ = try CaptureEvidenceReader.read(reference, from: url, maxCapturedLength: 4)
            }

            // Replacing the file changes its identity, invalidating the offset.
            try Data(ReplayCorpus.classicPcapBytes([Self.priorFrame, Self.priorFrame])).write(to: url)
            #expect(throws: PacketError.self) {
                _ = try CaptureEvidenceReader.read(reference, from: url)
            }
        }
    }

    // MARK: Cancellation publishes no result

    @Test
    func cancellationThrowsBeforeAnyResult() throws {
        try ReplayCorpus.withTemporaryFile(ReplayCorpus.classicPcapBytes(ReplayCorpus.conversation())) { url in
            let loader = try SavedCaptureStreamLoader(contentsOf: url, configuration: .init(isCancelled: { true }))
            #expect(throws: CancellationError.self) {
                _ = try loader.load()
            }
        }
    }

    // MARK: Named memory bounds

    @Test
    func retainedTailAndActivityStayBounded() throws {
        // 30 distinct single-frame sessions, one second apart.
        let frames = (0 ..< 30).map { index in
            ReplayCorpus.Frame(
                bytes: PacketBuilder.tlsClientHelloFrame(
                    sni: "b\(index).example", src: "198.51.100.30",
                    dst: "203.0.113.\(index % 200 + 1)", srcPort: UInt16(40_000 + index)
                ),
                offsetSeconds: index,
                linkType: LinkType.ethernet
            )
        }
        let expectedBytes = frames.reduce(0) { $0 + $1.bytes.count }
        try ReplayCorpus.withTemporaryFile(ReplayCorpus.classicPcapBytes(frames)) { url in
            let loader = try SavedCaptureStreamLoader(
                contentsOf: url, configuration: .init(retainedCapacity: 4, activityBucketCap: 8, progressStride: 1)
            )
            let result = try loader.load()
            #expect(result.totalFrames == 30)
            // Retained tail is bounded and reports eviction as local-window trim.
            #expect(result.retainedTail.count == 4)
            #expect(result.retainedTail.evictionCount == 26)
            // Activity is bounded but conserves exact totals.
            #expect(result.activity.buckets.count <= 8)
            #expect(result.activity.totalFrames == 30)
            #expect(result.activity.totalBytes == expectedBytes)
            #expect(result.activity.buckets.reduce(0) { $0 + $1.frameCount } == 30)
        }
    }

    @Test
    func progressIsMonotonicAndReachesTotalOnCleanEOF() throws {
        let frames = ReplayCorpus.conversation()
        let bytes = ReplayCorpus.classicPcapBytes(frames)
        let fileSize = UInt64(bytes.count)
        try ReplayCorpus.withTemporaryFile(bytes) { url in
            let collector = ProgressCollector()
            let loader = try SavedCaptureStreamLoader(contentsOf: url, configuration: .init(progressStride: 1))
            let result = try loader.load(onProgress: { collector.record($0) })
            let readings = collector.readings
            #expect(!readings.isEmpty)
            // Monotonic non-decreasing consumed bytes, constant known total.
            for pair in zip(readings, readings.dropFirst()) {
                #expect(pair.1.bytesConsumed >= pair.0.bytesConsumed)
            }
            #expect(readings.allSatisfy { $0.totalBytes == fileSize })
            // Clean EOF reaches the total.
            #expect(result.finalProgress.bytesConsumed == fileSize)
            #expect(result.finalProgress.totalBytes == fileSize)
            #expect(result.completeness == .complete)
        }
    }

    // MARK: Sparse multi-GiB early-start cancellation

    @Test
    func sparseMultiGigabyteStartsEarlyThenCancels() throws {
        let frame = Self.priorFrame
        let prefix = ReplayCorpus.classicPcapBytes([frame])
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("replay-sparse-\(UUID().uuidString).pcap")
        defer { try? FileManager.default.removeItem(at: url) }
        try Data(prefix).write(to: url)

        let sparseSize: UInt64 = 4 * 1_024 * 1_024 * 1_024
        let writer = try FileHandle(forWritingTo: url)
        try writer.truncate(atOffset: sparseSize)
        try writer.close()

        let calls = Counter()
        let reader = try CaptureStreamReader(
            contentsOf: url, configuration: .init(isCancelled: { calls.next() >= 3 })
        )
        // The whole sparse span is the declared total, but it is never walked.
        #expect(reader.identity.size == sparseSize)

        // The first real frame yields incrementally, before the sparse tail.
        guard case let .frame(event) = try reader.next() else {
            Issue.record("expected the first frame before the sparse tail")
            return
        }
        #expect(event.bytes == frame.bytes)
        #expect(event.progress.totalBytes == sparseSize)

        // Cancellation fires before the next bounded read, so the tail is never read.
        #expect(throws: CancellationError.self) {
            _ = try reader.next()
        }
    }

    // MARK: Private

    /// Collects coalesced progress callbacks synchronously on the load executor.
    private final class ProgressCollector {
        private(set) var readings: [PcapStreamProgress] = []

        func record(_ progress: PcapStreamProgress) {
            readings.append(progress)
        }
    }

    /// A monotonic call counter for the sparse cancellation closure.
    private final class Counter: @unchecked Sendable {
        // MARK: Internal

        func next() -> Int {
            lock.lock()
            defer { lock.unlock() }
            count += 1
            return count
        }

        // MARK: Private

        private let lock = NSLock()
        private var count = 0
    }

    /// A single well-formed session frame with a reserved example host, for the
    /// prior-session-recovery and evidence cases.
    private static let priorFrame = ReplayCorpus.Frame(
        bytes: PacketBuilder.tlsClientHelloFrame(
            sni: "prior.example", src: "198.51.100.40", dst: "203.0.113.90", srcPort: 41_000
        ),
        offsetSeconds: 1,
        linkType: LinkType.ethernet
    )

    private static func microTicks(_ offsetSeconds: Int) -> UInt64 {
        UInt64(1_700_000_000 + offsetSeconds) * 1_000_000
    }
}
